### ISSUE TITLE
Python error related to re.groups()

### ISSUE THREAD

**Issue by eliheuer** [alif-type/sfd2ufo#11]
With `Python 3.9.2` on `macOS 11.2` I'm trying to convert some `sfd` files to `ufo`, but I get this error:
```
$ sfd2ufo Font.sfd Font.ufo

Traceback (most recent call last):
  File "/Users/eli/Py/python-main/bin/sfd2ufo", line 33, in <module>
    sys.exit(load_entry_point('sfdLib', 'console_scripts', 'sfd2ufo')())
  File "/Users/eli/Py/repos/sfdLib/Lib/sfdLib/__main__.py", line 37, in main
    parser.parse()
  File "/Users/eli/Py/repos/sfdLib/Lib/sfdLib/parser.py", line 1323, in parse
    idx, quadratic, name, _ = m.groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by khaledhosny** [comment]
Can you send me the font?

**Comment by eliheuer** [comment]
Yes, it's the Rashi fonts from Mekorot: https://github.com/googlefonts/mekorot/tree/main/archive/sourceforge/Rashi/src

Thank you! 

I would be happy to make a pull request fixing this, I just haven't been able to figure out what needs to be done yet.

**Comment by khaledhosny** [comment]
There were two issue with this font, both should be fixed now.

**Comment by eliheuer** [comment]
Thank you so much! I just tested the two fixes and it works for me.
