### ISSUE TITLE
Consider using `sfdutf7`

### ISSUE THREAD

**Issue by ctrlcctrlv** [alif-type/sfd2ufo#13]
It can dump in a FontForge-readable format as well as read, and is tested against libfontforge.so.

https://github.com/ctrlcctrlv/sfdutf7.py

**Comment by khaledhosny** [comment]
I’m actually no longer interested in maintaining this library, since I just ported my last font project away from FontForge SFD. Would you be interested in taking over its maintenance?

**Comment by alerque** [comment]
c.f. #10. Fredrick has more font forge experience than I do by far, but I could pitch in a little here and there. Perhaps @fontforge, @source-foundry, @MFEK, or some other org home could be found for this. The `sfdnormalize` project might do well with a similar umbrella too.

**Comment by ctrlcctrlv** [comment]
Sure, I don't mind. That probably makes a lot of sense since I'm going to need both sfdnormalize and this library for the long-term.

**Comment by khaledhosny** [comment]
May be the three repositories can be moved to the FontForge GitHub organization.

**Comment by ctrlcctrlv** [comment]
Ahha, there's something of an impression I'm somehow in charge of @FontForge, but I'm not, just a contributor (and not the most active one as of late). I don't *mind* if that's what ends up happening but these tools are not really FontForge project-related in that their purpose is moving fonts away from FontForge, so I'd suggest @MFEK is the right organization.

**Comment by ctrlcctrlv** [comment]
(Also there's the matter of [Fontforge CG #D5](https://github.com/fontforge/fontforge/wiki/Community-guidelines#D5):

> ## D5: SFD is not intended for external consumption
>
> It is not a bug in FontForge if an external program, free or proprietary, has trouble with some SFD file FontForge itself doesn't have trouble with. [№4339](https://github.com/fontforge/fontforge/issues/4339), therefore, is not generally fixable other than by improving the error message.
>
> When we make changes to the SFD format, we only think about ourselves, and not external programs which are, at their own risk, using our internal format.
>
> If you need some SFD-only data, the right way to get it is through implementing, or making a new, [UFO format extension](http://unifiedfontobject.org/versions/ufo3/glyphs/glif/#lib).

)

Although I authored this document it doesn't perfectly reflect either my personal viewpoint then (or my viewpoint now), I was just trying to summarize consensus that was at the time trying to get people to fix FontForge's UFO export rather than work on tools like this.

Very unfortunately @frank-trampe, who wrote the UFO export in C, hasn't been able to be around lately on the project and I personally find sfdnormalize and sfdLib easier to work with as I'm not the best C programmer (but far from the worst)…so I think that absolutely these tools are the future of getting UFO's from SFD's, regardless of what may have been true or thought to be true a few years ago.

**Comment by khaledhosny** [comment]
I didn’t mean to imply anything. FontForge seemed a natural place for something that reads FontForge format (and I know that back in the day, George Williams were open to the idea others would adopt SFD format instead of UFO, and that is probably why he documented it).

But I don’t really care that much, whatever works for you. Just tell me where you want to to transfer the repository, and I’ll transfer it.

**Comment by ctrlcctrlv** [comment]
https://github.com/MFEK

**Comment by khaledhosny** [comment]
I tried but I get a “ You don’t have the permission to create public repositories on MFEK” error message.

**Comment by khaledhosny** [comment]
I invited you as an admin to this repository, so you can transfer it yourself.

**Comment by ctrlcctrlv** [comment]
As there was no objection I did the transfer, and will close this soon.
