### ISSUE TITLE
Please explain why this exists

### ISSUE THREAD

**Issue by davelab6** [alif-type/sfd2ufo#3]
FontForge's native UFO export passes all sorts of round-trip tests. 

Are there any specific issues with the native export that led you to develop this? :)

cc @frank-trampe

**Comment by khaledhosny** [comment]
FontForge does not export UFO kerning, for one (last I checked).

Also hacking < 300 lines of Python code is much easier than hacking FontForge’s > 4000 lines of C code that do basically the same thing or even less.

Even if I started parsing SFD files myself, it will still be much shorter than FontForge’s UFO code alone.
