### ISSUE TITLE
Add a font builder

### ISSUE THREAD

**Issue by khaledhosny** [alif-type/sfd2ufo#8]
This would take the parsed SFD font an build a binary font out of it, essentially providing a pure Python pipeline for building SFD fonts.

**Comment by anthrotype** [comment]
Interesting. Why not instead hook sfd2ufo into the existing UFO pipeline and build the OTF from it?

**Comment by anthrotype** [comment]
I mean fontmake

**Comment by khaledhosny** [comment]
That should be possible already using the UFO files we generate, but there are many features of SFD files that can’t be represented in UFO, and a way to build fonts that make use of such features would be nice.

Anyway it is a long term goal when I need something to keep me busy, I have no urgent need for this.

**Comment by davelab6** [comment]
Adrien might have some comments on this

**Comment by khaledhosny** [comment]
Sticking with FontForge, it might be rusty but at least it works.
