### ISSUE TITLE
Integrate into fontmake?

### ISSUE THREAD

**Issue by behdad** [alif-type/sfd2ufo#9]
Should we integrate this into fontmake? In a future where ufoLib is moved to fonttools, maybe even move this to fonttools?

@anthrotype

**Comment by khaledhosny** [comment]
I haven’t considered this before, but it makes sense I guess (there are some FontForge features that can’t be represented in UFO, but I think they are not that crucial). I just need to support parsing contextual lookups and probably do some tidying before this.

**Comment by anthrotype** [comment]
sgtm

**Comment by khaledhosny** [comment]
Not working on this anymore.
